-- ========================================================
-- QU CONNECT DATABASE SCHEMA & SEED DATA
-- Run this script in your Supabase SQL Editor to set up
-- the required tables, relations, check constraints, and seed data.
-- ========================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- 1. MASTER TABLES
-- --------------------------------------------------------

-- colleges table
CREATE TABLE IF NOT EXISTS public.colleges (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_ar text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- majors table
CREATE TABLE IF NOT EXISTS public.majors (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    college_id bigint REFERENCES public.colleges(id) ON DELETE CASCADE NOT NULL,
    name_ar text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- interests table
CREATE TABLE IF NOT EXISTS public.interests (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category text NOT NULL, -- e.g. 'Technology', 'Creative', 'Sports', 'Entertainment', 'Community'
    name_ar text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- goals table
CREATE TABLE IF NOT EXISTS public.goals (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name_ar text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- --------------------------------------------------------
-- 2. USER PROFILE & DATA TABLES
-- --------------------------------------------------------

-- profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    student_id text UNIQUE NOT NULL,
    first_name text NOT NULL,
    college_id bigint REFERENCES public.colleges(id) ON DELETE SET NULL,
    major_id bigint REFERENCES public.majors(id) ON DELETE SET NULL,
    academic_level integer CHECK (academic_level >= 1 AND academic_level <= 10),
    bio text,
    avatar_url text DEFAULT '🎓',
    gender_group text NOT NULL CHECK (gender_group IN ('male', 'female')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- user_interests table
CREATE TABLE IF NOT EXISTS public.user_interests (
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    interest_id bigint REFERENCES public.interests(id) ON DELETE CASCADE NOT NULL,
    importance integer DEFAULT 0 CHECK (importance IN (0, 1, 2)), -- 0: interested, 1: important, 2: very important
    PRIMARY KEY (user_id, interest_id)
);

-- user_goals table
CREATE TABLE IF NOT EXISTS public.user_goals (
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    goal_id bigint REFERENCES public.goals(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (user_id, goal_id)
);

-- social_preferences table
CREATE TABLE IF NOT EXISTS public.social_preferences (
    user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    communication_type text NOT NULL CHECK (communication_type IN ('chat', 'study', 'group', 'activities')),
    personality_preference text, -- comma-separated list of values
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- connections table
CREATE TABLE IF NOT EXISTS public.connections (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    requester_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    recipient_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status text NOT NULL CHECK (status IN ('pending', 'accepted', 'declined')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (requester_id, recipient_id)
);

-- --------------------------------------------------------
-- 3. ROW-LEVEL SECURITY (RLS) POLICIES
-- --------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.majors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.connections ENABLE ROW LEVEL SECURITY;

-- Colleges: Allow select for anyone, modify for admin/service_role only
CREATE POLICY "Allow public read access to colleges" ON public.colleges FOR SELECT TO public USING (true);

-- Majors: Allow select for anyone
CREATE POLICY "Allow public read access to majors" ON public.majors FOR SELECT TO public USING (true);

-- Interests: Allow select for anyone
CREATE POLICY "Allow public read access to interests" ON public.interests FOR SELECT TO public USING (true);

-- Goals: Allow select for anyone
CREATE POLICY "Allow public read access to goals" ON public.goals FOR SELECT TO public USING (true);

-- Profiles: Allow read for same gender only, insert/update/delete for own row
CREATE POLICY "Allow same-gender read access to profiles" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id OR gender_group = (SELECT gender_group FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow individual insert to profiles" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow individual update to profiles" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow individual delete to profiles" ON public.profiles FOR DELETE TO authenticated USING (auth.uid() = id);

-- User Interests: Allow read for same gender only, insert/update/delete for own row
CREATE POLICY "Allow same-gender read access to user_interests" ON public.user_interests FOR SELECT TO authenticated USING (user_id = auth.uid() OR (SELECT gender_group FROM public.profiles WHERE id = user_id) = (SELECT gender_group FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow individual insert to user_interests" ON public.user_interests FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow text update to user_interests" ON public.user_interests FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow individual delete to user_interests" ON public.user_interests FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- User Goals: Allow read for same gender only, insert/update/delete for own row
CREATE POLICY "Allow same-gender read access to user_goals" ON public.user_goals FOR SELECT TO authenticated USING (user_id = auth.uid() OR (SELECT gender_group FROM public.profiles WHERE id = user_id) = (SELECT gender_group FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow individual insert to user_goals" ON public.user_goals FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow individual update to user_goals" ON public.user_goals FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow individual delete to user_goals" ON public.user_goals FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Social Preferences: Allow read for same gender only, insert/update/delete for own row
CREATE POLICY "Allow same-gender read access to social_preferences" ON public.social_preferences FOR SELECT TO authenticated USING (user_id = auth.uid() OR (SELECT gender_group FROM public.profiles WHERE id = user_id) = (SELECT gender_group FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow individual insert to social_preferences" ON public.social_preferences FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow individual update to social_preferences" ON public.social_preferences FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow individual delete to social_preferences" ON public.social_preferences FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Connections: Allow read for involved users, insert for same-gender, update for recipient
CREATE POLICY "Allow individual read to connections" ON public.connections FOR SELECT TO authenticated USING (auth.uid() = requester_id OR auth.uid() = recipient_id);
CREATE POLICY "Allow individual insert to connections" ON public.connections FOR INSERT TO authenticated WITH CHECK (auth.uid() = requester_id AND (SELECT gender_group FROM public.profiles WHERE id = requester_id) = (SELECT gender_group FROM public.profiles WHERE id = recipient_id));
CREATE POLICY "Allow individual update to connections" ON public.connections FOR UPDATE TO authenticated USING (auth.uid() = recipient_id) WITH CHECK (auth.uid() = recipient_id);

-- --------------------------------------------------------
-- 4. SEED DATA
-- --------------------------------------------------------

-- Seed Colleges
INSERT INTO public.colleges (id, name_ar) VALUES
(1, 'كلية الحاسب'),
(2, 'كلية الهندسة'),
(3, 'كلية العلوم'),
(4, 'كلية إدارة الأعمال'),
(5, 'كلية الطب البشري')
ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar;

-- Seed Majors
INSERT INTO public.majors (id, college_id, name_ar) VALUES
(1, 1, 'علوم الحاسب'),
(2, 1, 'هندسة الحاسب'),
(3, 1, 'تقنية المعلومات'),
(4, 1, 'الأمن السيبراني'),
(5, 2, 'هندسة كهربائية'),
(6, 2, 'هندسة ميكانيكية'),
(7, 2, 'هندسة مدنية'),
(8, 2, 'هندسة كيميائية'),
(9, 3, 'رياضيات'),
(10, 3, 'فيزياء'),
(11, 3, 'كيمياء'),
(12, 3, 'علم الأحياء'),
(13, 4, 'محاسبة'),
(14, 4, 'تمويل وبنوك'),
(15, 4, 'إدارة أعمال'),
(16, 4, 'تسويق'),
(17, 4, 'نظم معلومات إدارية'),
(18, 5, 'الطب والجراحة')
ON CONFLICT (id) DO UPDATE SET college_id = EXCLUDED.college_id, name_ar = EXCLUDED.name_ar;

-- Seed Interests
INSERT INTO public.interests (id, category, name_ar) VALUES
(1, 'Technology', 'الذكاء الاصطناعي'),
(2, 'Technology', 'برمجة وتطوير'),
(3, 'Technology', 'أمن سيبراني'),
(4, 'Technology', 'تصميم واجهات'),
(5, 'Entertainment', 'الأنمي'),
(6, 'Entertainment', 'ألعاب الفيديو'),
(7, 'Entertainment', 'أفلام ومسلسلات'),
(8, 'Entertainment', 'موسیقی'),
(9, 'Sports', 'كرة القدم'),
(10, 'Sports', 'كرة السلة'),
(11, 'Sports', 'بادل'),
(12, 'Sports', 'لياقة بدنية'),
(13, 'Creative', 'التصوير'),
(14, 'Creative', 'التصميم الجرافيكي'),
(15, 'Creative', 'الرسم'),
(16, 'Creative', 'كتابة إبداعية'),
(17, 'Community', 'التطوع'),
(18, 'Community', 'ريادة الأعمال'),
(19, 'Community', 'الأندية الطلابية'),
(20, 'Community', 'النقاشات العامة')
ON CONFLICT (id) DO UPDATE SET category = EXCLUDED.category, name_ar = EXCLUDED.name_ar;

-- Seed Goals
INSERT INTO public.goals (id, name_ar) VALUES
(1, 'شريك مذاكرة'),
(2, 'أصدقاء جدد'),
(3, 'توجيه وإرشاد'),
(4, 'أنشطة وفعاليات')
ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar;
